# Generated by Django 5.1.2 on 2024-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_spot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='distance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='node',
            field=models.BigIntegerField(unique=True),
        ),
    ]
