# Generated by Django 4.1.7 on 2024-09-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_mytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
