# Generated by Django 5.1.2 on 2024-11-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_alter_mapdata_distance_alter_mapdata_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdata',
            old_name='idx',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='idx',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='idx',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='idx',
            new_name='id',
        ),
    ]
