# Generated by Django 4.1.7 on 2024-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_delete_mytable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is_superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
