# Generated by Django 5.1.2 on 2024-11-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_rename_idx_mapdata_id_rename_idx_node_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdata',
            old_name='id',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='id',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='id',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='id',
            new_name='idx',
        ),
    ]
