# Generated by Django 4.1.7 on 2024-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_remove_user_birth_date_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=10, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='tags',
            field=models.ManyToManyField(blank=True, to='routing.tag'),
        ),
    ]
