# Generated by Django 4.1.7 on 2024-09-30 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_tag_remove_user_account_id_remove_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.spot')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
