# Generated by Django 4.1.7 on 2024-10-19 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_rename_langitude_spot_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapdata',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('aim_tags', models.TextField()),
                ('html', models.TextField()),
                ('goal_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_spot', to='routing.spot')),
                ('start_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_spot', to='routing.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('via_spots', models.ManyToManyField(related_name='via_spots', to='routing.spot')),
            ],
        ),
    ]
