# Generated by Django 4.1.7 on 2024-10-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_node_rename_latitude_spot_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='lon',
            new_name='longitude',
        ),
    ]
