# Generated by Django 5.1.2 on 2024-11-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0013_alter_node_table_alter_spot_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='node',
            table=None,
        ),
        migrations.AlterModelTable(
            name='spot',
            table=None,
        ),
    ]
